### ISSUE TITLE
slist includes items in directory where `slist` is called

### ISSUE THREAD

**Issue by houdinisparks** [GovTechSG/slist#11]
Installation steps taken:
```
git clone https://github.com/GovTechSG/slist.git
cd slist
chmod +x slist.sh
ln -s ${PWD}/slist.sh /usr/local/bin/slist
```
symlinks look fine:
```bash
$ ll /usr/local/bin/slist
lrwxr-xr-x  1 a662176  admin    29B Mar 18 17:17 /usr/local/bin/slist -> /Users/a662176/slist/slist.sh
```

Error Observed:

```
$ slist
```

![image](https://user-images.githubusercontent.com/12453872/54520984-f0819880-49a4-11e9-8eae-eaa5c3c4a9bf.png)

Item 1. 2. 3. shouldnt be there

The items in the directory slist was called are also included in the list, any idea if its due to my set-up?

Here is the strucutre my config file for you ref:

```
Host *
  UseKeychain yes

Host alias1
   User ubuntu
   Hostname 1.1.1.1
   Port 22
   ForwardAgent yes


...

Host aliasn
   User ubuntu
   Hostname 1.1.1.1
   Port 22
   ForwardAgent yes

```

**Comment by alvinsiew** [comment]
Issues fixed
